"""init2

Revision ID: 301d45fa16fe
Revises: fb2b77c382e5
Create Date: 2025-02-03 21:47:17.884914

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '301d45fa16fe'
down_revision: Union[str, None] = 'fb2b77c382e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
